export const UNITS = {
  KNIGHT: {
    id: 'knight',
    name: 'Knight',
    cost: 3,
    hp: 600,
    damage: 75,
    speed: 1.5,
    range: 1,
    attackSpeed: 1.2,
    type: 'ground',
    count: 1,
  },
  ARCHER: {
    id: 'archer',
    name: 'Archer',
    cost: 3,
    hp: 250,
    damage: 45,
    speed: 1.8,
    range: 5,
    attackSpeed: 1.0,
    type: 'ground',
    count: 1,
  },
  GIANT: {
    id: 'giant',
    name: 'Giant',
    cost: 5,
    hp: 2000,
    damage: 120,
    speed: 0.8,
    range: 1,
    attackSpeed: 1.5,
    type: 'ground',
    target: 'building',
    count: 1,
  },
  WIZARD: {
    id: 'wizard',
    name: 'Wizard',
    cost: 4,
    hp: 350,
    damage: 100,
    speed: 1.4,
    range: 4.5,
    attackSpeed: 1.4,
    type: 'ground',
    splash: 2,
    count: 1,
  },
  SKELETONS: {
    id: 'skeletons',
    name: 'Skeletons',
    cost: 2,
    hp: 50,
    damage: 30,
    speed: 2.0,
    range: 1,
    attackSpeed: 1.0,
    type: 'ground',
    count: 5,
  },
  CANNON: {
    id: 'cannon',
    name: 'Mobile Cannon',
    cost: 3,
    hp: 600,
    damage: 80,
    speed: 0.6,
    range: 6,
    attackSpeed: 1.5,
    type: 'ground',
    count: 1,
  },
  BOMBER: {
    id: 'bomber',
    name: 'Bomber',
    cost: 2,
    hp: 150,
    damage: 100,
    speed: 1.6,
    range: 3,
    attackSpeed: 1.6,
    type: 'ground',
    splash: 2,
    count: 1,
  },
  KAMIKAZE: {
    id: 'kamikaze',
    name: 'Kamikaze',
    cost: 2,
    hp: 100,
    damage: 500,
    speed: 3.0,
    range: 0.5,
    attackSpeed: 0,
    type: 'ground',
    selfDestruct: true,
    splash: 2.5,
    count: 1,
  },
  FIREBALL: {
    id: 'fireball',
    name: 'Fireball',
    cost: 4,
    damage: 400,
    type: 'spell',
    radius: 2.5,
  },
  MANA_COLLECTOR: {
    id: 'mana_collector',
    name: 'Mana Collector',
    cost: 5,
    hp: 800,
    type: 'building',
    lifetime: 40,
    manaProduction: 1,
    productionInterval: 5,
  },
  SNIPER: {
    id: 'sniper',
    name: 'Sniper',
    cost: 4,
    hp: 200,
    damage: 150,
    speed: 1.2,
    range: 8,
    attackSpeed: 2.0,
    type: 'ground',
    count: 1,
  },
  GOBLIN_HUT: {
    id: 'goblin_hut',
    name: 'Goblin Hut',
    cost: 5,
    hp: 800,
    type: 'building',
    lifetime: 40,
    spawnUnit: 'goblin',
    spawnInterval: 4,
  },
  GOBLIN: {
    id: 'goblin',
    name: 'Goblin',
    cost: 2,
    hp: 100,
    damage: 80,
    speed: 2.5,
    range: 0.5,
    attackSpeed: 1.0,
    type: 'ground',
    count: 1,
  },
  TOWER: {
    id: 'tower',
    name: 'King Tower',
    hp: 3000,
    damage: 90,
    range: 7,
    attackSpeed: 0.8,
    type: 'building',
  }
};

export const GAME_CONFIG = {
  MANA_REGEN_RATE: 0.5,
  MAX_MANA: 10,
  FIELD_WIDTH: 10,
  FIELD_HEIGHT: 18,
  FPS: 30,
};
