export const UNITS = {
  // === 1 코스트: 사이클 & 물량 ===
  SKELETONS: {
    id: 'skeletons',
    name: 'Skeletons',
    cost: 1,
    hp: 100,
    damage: 67,
    speed: 2.5,
    range: 1,
    attackSpeed: 1.0,
    type: 'ground',
    count: 6,
  },

  // === 2 코스트: 저렴한 유틸리티 ===
  GOBLIN: {
    id: 'goblin',
    name: 'Goblin',
    cost: 2,
    hp: 150,
    damage: 100,
    speed: 2.5,
    range: 0.5,
    attackSpeed: 1.1,
    type: 'ground',
    count: 2, // 2마리 소환
  },

  // === 3 코스트: 기본 전투 유닛 ===
  KNIGHT: {
    id: 'knight',
    name: 'Knight',
    cost: 3,
    hp: 1500,
    damage: 150,
    speed: 1.2,
    range: 1,
    attackSpeed: 1.1,
    type: 'ground',
    count: 1,
  },
  ARCHER: {
    id: 'archer',
    name: 'Archer',
    cost: 3,
    hp: 252,
    damage: 89,
    speed: 1.4,
    range: 5.5,
    attackSpeed: 1.2,
    type: 'ground',
    count: 2,
  },
  BOMBER: {
    id: 'bomber',
    name: 'Bomber',
    cost: 3,
    hp: 205,
    damage: 133,
    speed: 1.6,
    range: 4.5,
    attackSpeed: 1.9,
    type: 'ground',
    splash: 1.5,
    count: 1,
  },
  KAMIKAZE: {
    id: 'kamikaze',
    name: 'Kamikaze',
    cost: 3,
    hp: 180,
    damage: 700,
    speed: 3.5,
    range: 0.5,
    attackSpeed: 0,
    type: 'ground',
    selfDestruct: true,
    splash: 2.5,
    count: 1,
  },

  // === 4 코스트: 특수 유닛 & 스펠 ===
  CANNON: {
    id: 'cannon',
    name: 'Cannon',
    cost: 4,
    hp: 597,
    damage: 147,
    speed: 0.7,
    range: 6,
    attackSpeed: 0.9,
    type: 'ground',
    count: 1,
    projectile: 'cannonball',
    projectileSpeed: 10,
  },
  SNIPER: {
    id: 'sniper',
    name: 'Sniper',
    cost: 4,
    hp: 272,
    damage: 240,
    speed: 1.0,
    range: 10,
    attackSpeed: 3.0,
    type: 'ground',
    count: 1,
    projectile: 'bullet',
    projectileSpeed: 20,
  },
  VALKYRIE: {
    id: 'valkyrie',
    name: 'Valkyrie',
    cost: 4,
    hp: 1600,
    damage: 220,
    speed: 1.5,
    range: 1,
    attackSpeed: 1.5,
    type: 'ground',
    splash: 1.5,
    count: 1,
  },
  HOG_RIDER: {
    id: 'hog_rider',
    name: 'Hog Rider',
    cost: 4,
    hp: 1400,
    damage: 260,
    speed: 2.5,
    range: 1,
    attackSpeed: 1.6,
    type: 'ground',
    favoriteTarget: 'building',
    count: 1,
  },
  BABY_DRAGON: {
    id: 'baby_dragon',
    name: 'Baby Dragon',
    cost: 4,
    hp: 1000,
    damage: 130,
    speed: 1.8,
    range: 3,
    attackSpeed: 1.5,
    type: 'flying',
    splash: 1.5,
    count: 1,
    projectile: 'fireball_small',
    projectileSpeed: 8,
  },
  FIREBALL: {
    id: 'fireball',
    name: 'Fireball',
    cost: 6,
    damage: 650,
    type: 'spell',
    radius: 1.5,
  },
  TORNADO: {
    id: 'tornado',
    name: 'Tornado',
    cost: 3,
    type: 'spell',
    radius: 2.0,
    duration: 3,
    damagePerSecond: 50,
    pullForce: 3,
  },
  RAGE: {
    id: 'rage',
    name: 'Rage',
    cost: 2,
    type: 'spell',
    radius: 2.5,
    duration: 6,
    speedBuff: 1.35,
    attackSpeedBuff: 1.35,
  },
  HEAL: {
    id: 'heal',
    name: 'Heal',
    cost: 1,
    type: 'spell',
    radius: 2.0,
    duration: 3,
    healPerSecond: 100,
  },

  // === 5 코스트: 강력한 유닛 & 건물 ===
  GIANT: {
    id: 'giant',
    name: 'Giant',
    cost: 5,
    hp: 3275,
    damage: 200,
    speed: 1.0,
    range: 1,
    attackSpeed: 1.5,
    type: 'ground',
    target: 'building',
    count: 1,
  },
  WIZARD: {
    id: 'wizard',
    name: 'Wizard',
    cost: 5,
    hp: 598,
    damage: 169,
    speed: 1.4,
    range: 5.5,
    attackSpeed: 1.7,
    type: 'ground',
    splash: 2,
    count: 1,
    projectile: 'fireball_small',
    projectileSpeed: 9,
  },
  WITCH: {
    id: 'witch',
    name: 'Witch',
    cost: 5,
    hp: 700,
    damage: 70,
    speed: 1.2,
    range: 5,
    attackSpeed: 0.7,
    type: 'ground',
    splash: 1.0,
    spawnUnit: 'skeletons',
    spawnInterval: 7,
    spawnCount: 3,
    count: 1,
    projectile: 'magic_bolt',
    projectileSpeed: 9,
  },
  BARBARIANS: {
    id: 'barbarians',
    name: 'Barbarians',
    cost: 5,
    hp: 600,
    damage: 150,
    speed: 1.5,
    range: 1,
    attackSpeed: 1.4,
    type: 'ground',
    count: 4,
  },
  BALLOON: {
    id: 'balloon',
    name: 'Balloon',
    cost: 5,
    hp: 1396,
    damage: 600,
    speed: 1.5,
    range: 0.5,
    attackSpeed: 3.0,
    type: 'flying',
    favoriteTarget: 'building',
    deathDamage: 200,
    deathDamageRadius: 3,
    count: 1,
  },
  GOBLIN_HUT: {
    id: 'goblin_hut',
    name: 'Goblin Hut',
    cost: 5,
    hp: 1007,
    type: 'building',
    lifetime: 40,
    spawnUnit: 'goblin',
    spawnInterval: 6,
  },

  // === 6 코스트: 투자형 건물 ===
  MANA_COLLECTOR: {
    id: 'mana_collector',
    name: 'Mana Collector',
    cost: 8,
    hp: 3400,
    type: 'building',
    lifetime: 60,
    manaProduction: 0.5,
    productionInterval: 3.5,
  },

  // === 타워 ===
  TOWER: {
    id: 'tower',
    name: 'King Tower',
    hp: 4008,
    damage: 100,
    range: 7,
    attackSpeed: 0.8,
    type: 'building',
  }
};

// 진화 스탯: 각 유닛마다 개별적으로 조정된 강화 스탯
export const EVOLVED_STATS = {
  // === 1 코스트 ===
  SKELETONS: {
    hp: 130,
    damage: 85,
    speed: 2.8,
    count: 10,
  },

  // === 2 코스트 ===
  GOBLIN: {
    hp: 200,
    damage: 130,
    speed: 2.8,
    attackSpeed: 0.95,
  },

  // === 3 코스트 ===
  KNIGHT: {
    hp: 2000,
    damage: 200,
    speed: 1.4,
  },
  ARCHER: {
    hp: 300,
    damage: 115,
    range: 6.5,
    attackSpeed: 1.0,
  },
  BOMBER: {
    hp: 250,
    damage: 180,
    splash: 2.0,
    speed: 1.8,
  },
  KAMIKAZE: {
    hp: 230,
    damage: 950,
    splash: 3.0,
    speed: 4.0,
  },

  // === 4 코스트 ===
  CANNON: {
    hp: 800,
    damage: 210,
    range: 7.0,
    attackSpeed: 0.75,
  },
  SNIPER: {
    hp: 350,
    damage: 320,
    range: 12,
    attackSpeed: 2.7,
    projectileSpeed: 25,
  },
  VALKYRIE: {
    hp: 2100,
    damage: 290,
    splash: 2.0,
    speed: 1.7,
  },
  HOG_RIDER: {
    hp: 1800,
    damage: 340,
    speed: 3.0,
    attackSpeed: 1.4,
  },
  BABY_DRAGON: {
    hp: 1350,
    damage: 175,
    splash: 2.0,
    speed: 2.1,
    range: 3.5,
  },

  // === 스펠 ===
  FIREBALL: {
    damage: 850,
    radius: 2.0,
  },
  TORNADO: {
    radius: 2.5,
    duration: 4,
    damagePerSecond: 70,
    pullForce: 4,
  },
  RAGE: {
    radius: 3.0,
    duration: 8,
    speedBuff: 1.5,
    attackSpeedBuff: 1.5,
  },
  HEAL: {
    radius: 2.5,
    duration: 4.5,
    healPerSecond: 150,
  },

  // === 5 코스트 ===
  GIANT: {
    hp: 4500,
    damage: 270,
    speed: 1.2,
    attackSpeed: 1.3,
  },
  WIZARD: {
    hp: 800,
    damage: 230,
    splash: 2.5,
    range: 6.5,
    attackSpeed: 1.5,
  },
  WITCH: {
    hp: 950,
    damage: 95,
    spawnInterval: 5.5,
    spawnCount: 4,
    range: 6.0,
  },
  BARBARIANS: {
    hp: 800,
    damage: 200,
    speed: 1.7,
    attackSpeed: 1.2,
    count: 5,
  },
  BALLOON: {
    hp: 1900,
    damage: 800,
    speed: 1.8,
    deathDamage: 300,
    deathDamageRadius: 3.5,
    attackSpeed: 2.7,
  },
  GOBLIN_HUT: {
    hp: 1400,
    lifetime: 55,
    spawnInterval: 5,
  },

  // === 6 코스트 ===
  MANA_COLLECTOR: {
    hp: 4500,
    lifetime: 80,
    manaProduction: 0.7,
    productionInterval: 3.0,
  },
};

export const GAME_CONFIG = {
  MANA_REGEN_RATE: 0.5,
  MAX_MANA: 20,
  FIELD_WIDTH: 10,
  FIELD_HEIGHT: 18,
  FPS: 30,
};
