const UNITS = {
    // === 1 코스트: 사이클 & 물량 ===
    SKELETONS: {
        id: 'skeletons',
        name: 'Skeletons',
        cost: 1,
        hp: 100,
        damage: 67,
        speed: 2.5,
        range: 1,
        attackSpeed: 1.0,
        type: 'ground',
        count: 10,
    },

    // === 2 코스트: 저렴한 유틸리티 ===
    GOBLIN: {
        id: 'goblin',
        name: 'Goblin',
        cost: 2,
        hp: 150,
        damage: 100,
        speed: 2.5,
        range: 0.5,
        attackSpeed: 1.1,
        type: 'ground',
        count: 2, // 2마리 소환
    },

    // === 3 코스트: 기본 전투 유닛 ===
    KNIGHT: {
        id: 'knight',
        name: 'Knight',
        cost: 3,
        hp: 1500,
        damage: 150,
        speed: 1.2,
        range: 1,
        attackSpeed: 1.1,
        type: 'ground',
        count: 1,
    },
    ARCHER: {
        id: 'archer',
        name: 'Archer',
        cost: 3,
        hp: 252,
        damage: 89,
        speed: 1.4,
        range: 5.5,
        attackSpeed: 1.2,
        type: 'ground',
        count: 2,
    },
    BOMBER: {
        id: 'bomber',
        name: 'Bomber',
        cost: 3,
        hp: 205,
        damage: 133,
        speed: 1.6,
        range: 4.5,
        attackSpeed: 1.9,
        type: 'ground',
        splash: 1.5,
        count: 1,
    },
    KAMIKAZE: {
        id: 'kamikaze',
        name: 'Kamikaze',
        cost: 3,
        hp: 180,
        damage: 700,
        speed: 3.5,
        range: 0.5,
        attackSpeed: 0,
        type: 'ground',
        selfDestruct: true,
        splash: 2.5,
        count: 1,
    },

    // === 4 코스트: 특수 유닛 & 스펠 ===
    CANNON: {
        id: 'cannon',
        name: 'Cannon',
        cost: 4,
        hp: 597,
        damage: 147,
        speed: 0.7,
        range: 6,
        attackSpeed: 0.9,
        type: 'ground',
        count: 1,
    },
    SNIPER: {
        id: 'sniper',
        name: 'Sniper',
        cost: 4,
        hp: 272,
        damage: 240,
        speed: 1.0,
        range: 10,
        attackSpeed: 3.0,
        type: 'ground',
        count: 1,
    },
    VALKYRIE: {
        id: 'valkyrie',
        name: 'Valkyrie',
        cost: 4,
        hp: 1600,
        damage: 220,
        speed: 1.5,
        range: 1,
        attackSpeed: 1.5,
        type: 'ground',
        splash: 1.5,
        count: 1,
    },
    HOG_RIDER: {
        id: 'hog_rider',
        name: 'Hog Rider',
        cost: 4,
        hp: 1400,
        damage: 260,
        speed: 2.5,
        range: 1,
        attackSpeed: 1.6,
        type: 'ground',
        favoriteTarget: 'building',
        count: 1,
    },
    BABY_DRAGON: {
        id: 'baby_dragon',
        name: 'Baby Dragon',
        cost: 4,
        hp: 1000,
        damage: 130,
        speed: 1.8,
        range: 3,
        attackSpeed: 1.5,
        type: 'flying',
        splash: 1.5,
        count: 1,
    },
    FIREBALL: {
        id: 'fireball',
        name: 'Fireball',
        cost: 6,
        damage: 650,
        type: 'spell',
        radius: 2.5,
    },

    // === 5 코스트: 강력한 유닛 & 건물 ===
    GIANT: {
        id: 'giant',
        name: 'Giant',
        cost: 5,
        hp: 3275,
        damage: 200,
        speed: 1.0,
        range: 1,
        attackSpeed: 1.5,
        type: 'ground',
        target: 'building',
        count: 1,
    },
    WIZARD: {
        id: 'wizard',
        name: 'Wizard',
        cost: 5,
        hp: 598,
        damage: 169,
        speed: 1.4,
        range: 5.5,
        attackSpeed: 1.7,
        type: 'ground',
        splash: 2,
        count: 1,
    },
    WITCH: {
        id: 'witch',
        name: 'Witch',
        cost: 5,
        hp: 700,
        damage: 70,
        speed: 1.2,
        range: 5,
        attackSpeed: 0.7,
        type: 'ground',
        splash: 1.0,
        spawnUnit: 'skeletons',
        spawnInterval: 7,
        spawnCount: 3,
        count: 1,
    },
    BARBARIANS: {
        id: 'barbarians',
        name: 'Barbarians',
        cost: 5,
        hp: 600,
        damage: 150,
        speed: 1.5,
        range: 1,
        attackSpeed: 1.4,
        type: 'ground',
        count: 4,
    },
    GOBLIN_HUT: {
        id: 'goblin_hut',
        name: 'Goblin Hut',
        cost: 5,
        hp: 1007,
        type: 'building',
        lifetime: 40,
        spawnUnit: 'goblin',
        spawnInterval: 6,
    },

    // === 6 코스트: 투자형 건물 ===
    MANA_COLLECTOR: {
        id: 'mana_collector',
        name: 'Mana Collector',
        cost: 8,
        hp: 400,
        type: 'building',
        lifetime: 60,
        manaProduction: 0.5,
        productionInterval: 3.5,
    },

    // === 타워 ===
    TOWER: {
        id: 'tower',
        name: 'King Tower',
        hp: 4008,
        damage: 100,
        range: 7,
        attackSpeed: 0.8,
        type: 'building',
    }
};

const GAME_CONFIG = {
    MANA_REGEN_RATE: 0.5,
    MAX_MANA: 20,
    FIELD_WIDTH: 10,
    FIELD_HEIGHT: 18,
    FPS: 30,
};

module.exports = { UNITS, GAME_CONFIG };
